"""add_enrichment_status_fields

Revision ID: 03dadcfda136
Revises: 479adf4597c0
Create Date: 2026-07-07 00:24:01.350775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03dadcfda136'
down_revision: Union[str, Sequence[str], None] = '479adf4597c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vt_enrichment_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('vt_enrichment_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('abuse_enrichment_status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('abuse_enrichment_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_analyses', schema=None) as batch_op:
        batch_op.drop_column('abuse_enrichment_error')
        batch_op.drop_column('abuse_enrichment_status')
        batch_op.drop_column('vt_enrichment_error')
        batch_op.drop_column('vt_enrichment_status')

    # ### end Alembic commands ###
