"""add advanced scoring signals

Revision ID: 479adf4597c0
Revises: 4be22584bb8c
Create Date: 2026-07-05 16:24:00.499523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479adf4597c0'
down_revision: Union[str, Sequence[str], None] = '4be22584bb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    server_default is set explicitly (and kept) on every new NOT NULL column
    -- SQLite rejects ADD COLUMN ... NOT NULL with no default on a table that
    already has rows, which any already-deployed instance of this app will.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspicious_tlds', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('url_shorteners', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('urgency_keywords', sa.JSON(), nullable=False, server_default='[]'))

    with op.batch_alter_table('attachment_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_double_extension', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('email_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_lookalike_domain', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('lookalike_of', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_punycode_domain', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_suspicious_sender_tld', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('urgency_keywords_found', sa.JSON(), nullable=False, server_default='[]'))

    with op.batch_alter_table('url_indicators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shortener', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_suspicious_tld', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_punycode', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_indicators', schema=None) as batch_op:
        batch_op.drop_column('is_punycode')
        batch_op.drop_column('is_suspicious_tld')
        batch_op.drop_column('is_shortener')

    with op.batch_alter_table('email_analyses', schema=None) as batch_op:
        batch_op.drop_column('urgency_keywords_found')
        batch_op.drop_column('is_suspicious_sender_tld')
        batch_op.drop_column('is_punycode_domain')
        batch_op.drop_column('lookalike_of')
        batch_op.drop_column('is_lookalike_domain')

    with op.batch_alter_table('attachment_indicators', schema=None) as batch_op:
        batch_op.drop_column('is_double_extension')

    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('urgency_keywords')
        batch_op.drop_column('url_shorteners')
        batch_op.drop_column('suspicious_tlds')

    # ### end Alembic commands ###
