"""initial schema

Revision ID: 4be22584bb8c
Revises: 
Create Date: 2026-07-05 15:43:27.777050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be22584bb8c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scoring_weights', sa.JSON(), nullable=False),
    sa.Column('brand_domains', sa.JSON(), nullable=False),
    sa.Column('url_suspicious_keywords', sa.JSON(), nullable=False),
    sa.Column('virustotal_key', sa.String(length=255), nullable=True),
    sa.Column('abuseipdb_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_table('email_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('stored_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('from_addr', sa.Text(), nullable=True),
    sa.Column('from_domain', sa.String(length=255), nullable=True),
    sa.Column('reply_to', sa.Text(), nullable=True),
    sa.Column('reply_domain', sa.String(length=255), nullable=True),
    sa.Column('return_path', sa.Text(), nullable=True),
    sa.Column('return_domain', sa.String(length=255), nullable=True),
    sa.Column('sender_ip', sa.String(length=64), nullable=True),
    sa.Column('spf', sa.String(length=16), nullable=False),
    sa.Column('dkim', sa.String(length=16), nullable=False),
    sa.Column('dmarc', sa.String(length=16), nullable=False),
    sa.Column('auth_headers_raw', sa.JSON(), nullable=False),
    sa.Column('header_issues', sa.JSON(), nullable=False),
    sa.Column('abuse_score', sa.Integer(), nullable=True),
    sa.Column('abuse_total_reports', sa.Integer(), nullable=True),
    sa.Column('abuse_country', sa.String(length=8), nullable=True),
    sa.Column('abuse_isp', sa.Text(), nullable=True),
    sa.Column('global_hashes', sa.JSON(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_analyses'))
    )
    with op.batch_alter_table('email_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_email_analyses_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_email_analyses_status', ['status'], unique=False)
        batch_op.create_index('ix_email_analyses_verdict', ['verdict'], unique=False)

    op.create_table('attachment_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('is_executable_like', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['email_analyses.id'], name=op.f('fk_attachment_indicators_analysis_id_email_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment_indicators'))
    )
    with op.batch_alter_table('attachment_indicators', schema=None) as batch_op:
        batch_op.create_index('ix_attachment_indicators_analysis_id', ['analysis_id'], unique=False)
        batch_op.create_index('ix_attachment_indicators_sha256', ['sha256'], unique=False)

    op.create_table('score_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['email_analyses.id'], name=op.f('fk_score_reasons_analysis_id_email_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_reasons'))
    )
    with op.batch_alter_table('score_reasons', schema=None) as batch_op:
        batch_op.create_index('ix_score_reasons_analysis_id', ['analysis_id'], unique=False)

    op.create_table('url_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('vt_malicious', sa.Integer(), nullable=False),
    sa.Column('vt_harmless', sa.Integer(), nullable=False),
    sa.Column('vt_suspicious', sa.Integer(), nullable=False),
    sa.Column('is_suspicious_keyword', sa.Boolean(), nullable=False),
    sa.Column('is_ip_host', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['email_analyses.id'], name=op.f('fk_url_indicators_analysis_id_email_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_url_indicators'))
    )
    with op.batch_alter_table('url_indicators', schema=None) as batch_op:
        batch_op.create_index('ix_url_indicators_analysis_id', ['analysis_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_indicators', schema=None) as batch_op:
        batch_op.drop_index('ix_url_indicators_analysis_id')

    op.drop_table('url_indicators')
    with op.batch_alter_table('score_reasons', schema=None) as batch_op:
        batch_op.drop_index('ix_score_reasons_analysis_id')

    op.drop_table('score_reasons')
    with op.batch_alter_table('attachment_indicators', schema=None) as batch_op:
        batch_op.drop_index('ix_attachment_indicators_sha256')
        batch_op.drop_index('ix_attachment_indicators_analysis_id')

    op.drop_table('attachment_indicators')
    with op.batch_alter_table('email_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_email_analyses_verdict')
        batch_op.drop_index('ix_email_analyses_status')
        batch_op.drop_index('ix_email_analyses_created_at')

    op.drop_table('email_analyses')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
